# src/g5/AccountBundle/Resources/config/doctrine/User.mongodb.yml

g5\AccountBundle\Document\User:
    type: document
    customId: true
    fields:
        id:
            id: true
            strategy: increment

    referenceMany:
        groups:
            targetDocument: g5\AccountBundle\Document\Group
