g5_movie_add:
    pattern: /add
    defaults: { _controller: g5MovieBundle:Movie:add }
    options:
        expose: true

g5_movie_search:
    pattern:  /search
    defaults: { _controller: g5MovieBundle:Movie:search }

g5_movie_lookup:
    pattern:  /lookup
    defaults: { _controller: g5MovieBundle:Search:lookup }
    methods:  [ "POST" ]
    options:
        expose: true

g5_movie_loadmeta:
    pattern: /loadmeta/{tmdbid}
    defaults: { _controller: g5MovieBundle:Search:loadmeta }
    options:
        expose: true
