g5_movie_index:
    pattern: /
    defaults: { _controller: g5MovieBundle:Movie:index }

g5_movie_add:
    pattern: /add/{tmdbId}
    defaults: { _controller: g5MovieBundle:Movie:add }
    options:
        expose: true

g5_movie_search:
    pattern:  /search
    defaults: { _controller: g5MovieBundle:Movie:search }
    options:
        expose: true

g5_movie_loadmeta:
    pattern: /loadmeta/{tmdbId}
    defaults: { _controller: g5MovieBundle:Movie:loadmeta }
    options:
        expose: true
