# ApiController

g5_movei_api_label_new:
    pattern: /api/label/new
    defaults: { _controller: g5MovieBundle:Api:labelNew }
    options:
        expose: true

g5_movie_api_label_find:
    pattern: /api/label/find
    defaults: { _controller: g5MovieBundle:Api:labelFind }
    options:
        expose: true

g5_movie_api_label_add:
    pattern: /api/label/add
    defaults: { _controller: g5MovieBundle:Api:labelAdd }
    options:
        expose: true

g5_movie_api_unlink:
    pattern: /api/unlink
    defaults: { _controller: g5MovieBundle:Api:unlink }
    options:
        expose: true

# LabelController

g5_movie_label_index:
    pattern: /label/{name}
    defaults: { _controller: g5MovieBundle:Label:index }
    options:
        expose: true

# MovieController

g5_movie_index:
    pattern: /{page}
    defaults: { _controller: g5MovieBundle:Movie:index, page: 1 }
    requirements:
        page: "\d+"

g5_movie_new:
    pattern: /new
    defaults: { _controller: g5MovieBundle:Movie:new }

g5_movie_add:
    pattern: /add
    defaults: { _controller: g5MovieBundle:Movie:add }
    requirements:
        _method: POST
    options:
        expose: true

g5_movie_search:
    pattern:  /searcho
    defaults: { _controller: g5MovieBundle:Movie:search }
    options:
        expose: true

g5_movie_search_tmdb:
    pattern: /search
    defaults: { _controller: g5MovieBundle:Movie:searchTmdb }
    options:
        expose: true

g5_movie_loadTmdbData:
    pattern: /loadTmdb
    defaults: { _controller: g5MovieBundle:Movie:loadTmdb }
    requirements:
        _method: POST
    options:
        expose: true
