# MovieController
g5_movie_new:
    pattern: /new
    defaults: { _controller: g5MovieBundle:Movie:new }

# ToolsController
g5_movie_tools_index:
    pattern: /tools
    defaults: { _controller: g5MovieBundle:Tools:index }
