# src/g5/UserBundle/Resources/config/doctrine/User.mongodb.yml

g5\UserBundle\Document\User:
    type: document
    fields:
        id:
            id: true
        # username:
        #     type: string
        #     length: 25
        # email:
        #     type: string
        #     length: 255
