parameters:
    database_driver:   pdo_sqlite
    database_host:     localhost
    database_port:     27017
    database_name:     mn_test
    database_user:     ~
    database_password: ~
    database_path:     ~

    mailer_transport:  smtp
    mailer_host:       localhost
    mailer_user:       ~
    mailer_password:   ~

    locale:            en
    secret:            c9f701ef4542e7caf82379d4c82a4ab6

    tmdb_api_key:      280b6c5e0a196cab61823305d553390a
