g5_home:
    resource: "@g5HomeBundle/Resources/config/routing.yml"
    prefix:   /

g5_account:
    resource: "@g5AccountBundle/Resources/config/routing.yml"
    prefix:   /account

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
