_movie_import:
    pattern:  /import
    defaults: { _controller: g5MovieBundle:Default:import }

_movie_profile:
    pattern:	/{page}
    defaults:	{ _controller: g5MovieBundle:Default:index, page: 1 }
    requirements: { page: \d+ }
    
_movie_add:
    pattern:  /add
    defaults: { _controller: g5MovieBundle:Default:add }
    
_movie_save_tmdb:
    pattern: /save
    defaults: { _controller: g5MovieBundle:Default:saveTmdb }

_wdt:
    resource: "@WebProfilerBundle/Resources/config/routing/wdt.xml"
    prefix:   /_wdt

_profiler:
    resource: "@WebProfilerBundle/Resources/config/routing/profiler.xml"
    prefix:   /_profiler

_configurator:
    resource: "@SensioDistributionBundle/Resources/config/routing/webconfigurator.xml"
    prefix:   /_configurator

_main:
    resource: routing.yml
