g5_home:
    resource: "@g5HomeBundle/Resources/config/routing.yml"
    prefix:   /

g5_movie:
    type: rest
    resource: "@g5MovieBundle/Resources/config/routing.yml"
    prefix:   /api

g5_account:
    resource: "@g5AccountBundle/Resources/config/routing.yml"
    prefix:   /account

g5_account_api:
    type: rest
    resource: "@g5AccountBundle/Resources/config/routing/api.yml"
    prefix:   /api

# FOSJsRouting
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

# FOSUserBundle
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix: /account

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"
