g5\MovieBundle\Document\Label:
    type: document
    repositoryClass: g5\MovieBundle\Repository\LabelRepository

    fields:
        id:
            id: true

        name:
            type: string

    referenceOne:
        user:
            targetDocument: g5\AccountBundle\Document\User
            # cascade: all
