# /src/g5/MovieBundle/Resources/config/serializer/Entity.Movie.yml

g5\MovieBundle\Entity\Movie:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
        title:
            expose: true
        release_date:
            expose: true
