g5_account_registration:
    pattern:  /registration
    defaults: { _controller: g5AccountBundle:Registration:index }

g5_account_create:
    pattern: /create
    defaults: { _controller: g5AccountBundle:Registration:create }
    requirements:
        _method: POST
