# src/g5/AccountBundle/Resources/config/validation.yml

g5\AccountBundle\Document\User:
    constraints:
         - Doctrine\Bundle\MongoDBBundle\Validator\Constraints\Unique: email
    properties:
        email:
            - Email: ~
